### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by Florent2** [planetruby/books#28]
I no longer have to time maintain http://www.allrubybooks.com/. I'm looking for someone willing to maintain. I'd transfer the domain name, the Netlify hosting account and the local scripts I use to generate the HTML page using this repo JSON data.

@ydakuka would you be interested in owning and maintaining http://www.allrubybooks.com/?

**Comment by geraldb** [comment]
@Florent2   Hello, sorry if I am late (one year).  I am the little humble rubyist behind Planet Ruby - currently running the Ruby Advend Calendar 2020 <https://planetruby.github.io/gems/>.  Anyways, what a great initiative your book collection -    I am in for the long term and I'd be happy to take over and update the ruby books collection.

In my case you would have to  transfer just this repo to the planetruby org, see <https://github.com/planetruby> - I would NOT need the domain name or the Netlify hosting account.

I try to rebuild with Jekyll and GitHub pages (but yeah having a copy of your scripts would help).
Let me know what you think?   Cheers. Prost. Greetings from Austria.

**Comment by Florent2** [comment]
@geraldb great! I've transferred the repo to your personal account.

Here is the script and the HTML template:

https://gist.github.com/Florent2/df8e144d97fabd8d3b4c1b289df6b22b
https://gist.github.com/Florent2/f8f24c4152a3d1b188dc0fc30eaaa053

Let me know if you have any question and when the book collection is available on Planet Ruby (no rush) I would put a redirect to it on http://www.allrubybooks.com/.

Thanks!

**Comment by geraldb** [comment]
@Florent2    Thank your for your trust.   I transfered the repo over to the planet ruby, see <> and added your template and script in the /attic directory.

Thank you for your patience - yes, the conversion / reboot will take some weeks  - the plan is to get it done in the next month(s) - in January / February 2021.  Thanks again for your patience. Yeah, a redirect would be great (until you retire the domain). All the best. Cheers. Prost.

**Comment by geraldb** [comment]
@Florent2    Update -  I have converted over everything to the new system (using jekyll / github pages and collections in yaml). Please have a look if you find any errors or something wrong.   A known bug for now is the missing last_update_on info.    Thanks again.  Cheers. Prost.    PS:   A redirect would be great to <http://planetruby.github.io/books/>.

**Comment by Florent2** [comment]
Great! I've put in place a DNS permanent redirect from allrubybooks.com & www.allrubybooks.com to https://planetruby.github.io/books/
